#!/bin/bash

if [ -z $1 ]
 then
  echo "Error: please pass sort parameter. kubectl top po cpu|ram"
  exit 1
elif [ $1 = "cpu" ]
  then
	kubectl top po | sort -nrk2

elif [ $1 = "ram" ]
  then
    kubectl top po | sort -nrk3

fi